name: node0
display: Node node0 Agent
description: A test agent
execute: thread
mainfile: node0.py
inherits:
   - DispatchAgent

methods:
   - name: test003
     help: Runs a test
     args: []

variables:
   - name: report_dir
     help: the full path of where to write the test reports
     type: string

