#!/bin/bash

# This script runs a unit test on the inner ops node

set -e
set -x

# Arguments. Example: ./run-test mrynge pegasus 001
DETER_USER=$1
DETER_PROJECT=$2
TEST=$3

TOP_DIR=`pwd`
DETER_USERS_HOST="users.isi.deterlab.net"
DETER_SSH_OPTS="-o StrictHostKeyChecking=no"

DETER_SSH="ssh -A $DETER_USER@$DETER_USERS_HOST"

# fill in the templates
for TEMPLATE in `find . -name \*.template | sort`; do
    TARGET=`echo "$TEMPLATE" | sed 's/\.template$//'`
    cp -a $TEMPLATE $TARGET
    echo " ... setting up $TARGET from the template $TEMPLATE"
    perl -p -i -e "s/\\[\\[DETER_USER\\]\\]/$DETER_USER/g" $TARGET
done

# create all the agent tarballs
for TID in `cd tests && ls`; do
    cd $TOP_DIR/tests/$TID/agents
    for AGENT in `ls | grep -v tar.gz`; do
        (cd $AGENT && \
         cp -r ../../../../common/DeterLabTesting . && \
         tar czf ../$AGENT.tar.gz . && \
         rm -rf DeterLabTesting)
    done
done

# copy over files - two hops!
cd $TOP_DIR
mkdir -p reports/$TEST
rm -f reports/$TEST/*.xml >/dev/null 2>&1 || true
$DETER_SSH "rm -rf DETERLabTesting-ELabInElab ; mkdir DETERLabTesting-ELabInElab"
$DETER_SSH ". .profile && ssh $DETER_SSH_OPTS myops.test-elabinelab.$DETER_PROJECT 'rm -rf DETERLabTesting-ELabInElab'"
scp -q -r . $DETER_USER@$DETER_USERS_HOST:DETERLabTesting-ELabInElab/
$DETER_SSH "scp $DETER_SSH_OPTS -q -r DETERLabTesting-ELabInElab myops.test-elabinelab.$DETER_PROJECT:"

# fix permissions
$DETER_SSH ". .profile && ssh $DETER_SSH_OPTS myops.test-elabinelab.$DETER_PROJECT 'chmod 777 DETERLabTesting-ELabInElab/reports/$TEST'"

echo
echo
echo "#################################################"
echo "## Running test $TEST ..."
echo

# kill old projects
$DETER_SSH "ssh $DETER_SSH_OPTS myops.test-elabinelab.$DETER_PROJECT '. .profile && endexp -N -w $DETER_PROJECT test-$TEST >/dev/null 2>&1'" || true

echo "Deploying topology..."
$DETER_SSH "ssh $DETER_SSH_OPTS myops.test-elabinelab.$DETER_PROJECT '. .profile && cd DETERLabTesting-ELabInElab/tests/$TEST && startexp -N -w -i -a 120 -l 30 -E DeterLab_validation_test_$TEST -p $DETER_PROJECT -e test-$TEST topology.ns'"

# do we need to wait for things to settle down?
echo "Waiting for topology to be fully set up..."
sleep 5m

# get some basic exp info
echo
$DETER_SSH ". .profile && ssh $DETER_SSH_OPTS myops.test-elabinelab.$DETER_PROJECT 'cd DETERLabTesting-ELabInElab/tests/$TEST && expinfo -a $DETER_PROJECT test-$TEST'"

# run the orchestrator run
echo
##$DETER_SSH "ssh $DETER_SSH_OPTS control.test-$TEST.pegasus \"cd DETERLabTesting/tests/$TEST && timeout 15m /share/magi/current/magi_orchestrator.py --nocolor --project pegasus --experiment test-$TEST --events tests.aal\"" || true

# get the results
##scp -r $DETER_USER@$DETER_USERS_HOST:DETERLabTesting/reports/* reports/

# cleanup
##$DETER_SSH ". .profile && endexp -N -w $DETER_PROJECT test-$TEST"


